// Curated vocabulary bank: idioms, SAT-level words, and common American phrases.
// difficulty: 1 (easier) - 3 (harder), used only to order which new words surface first.

const idioms = [
  ['break the ice', 'to do or say something that relieves tension or starts a conversation in a social situation'],
  ['bite the bullet', 'to force yourself to endure something painful or unpleasant'],
  ['spill the beans', 'to reveal secret information, often unintentionally'],
  ['under the weather', 'feeling slightly ill'],
  ['hit the nail on the head', 'to describe exactly what is causing a situation or problem'],
  ['let the cat out of the bag', 'to reveal a secret carelessly or by mistake'],
  ['burn the midnight oil', 'to work late into the night'],
  ['cost an arm and a leg', 'to be very expensive'],
  ['on the same page', 'in agreement, or understanding something the same way as someone else'],
  ['once in a blue moon', 'very rarely'],
  ['the ball is in your court', 'it is up to you to make the next decision or move'],
  ['cut corners', 'to do something poorly or cheaply in order to save time or money'],
  ['back to the drawing board', 'to start an idea or plan over again because the previous one failed'],
  ['beat around the bush', 'to avoid talking about something directly'],
  ['get the ball rolling', 'to start something or get a process moving'],
  ['hit the ground running', 'to start something and proceed at a fast pace immediately'],
  ['in the same boat', 'facing the same difficult circumstances as someone else'],
  ['jump on the bandwagon', 'to join others in doing something popular or fashionable'],
  ['kill two birds with one stone', 'to accomplish two goals with a single action'],
  ['the last straw', 'the final problem in a series that makes a situation unbearable'],
  ['go the extra mile', 'to make a special extra effort to achieve something', 3],
  ['bark up the wrong tree', 'to pursue a mistaken or misguided course of action', 3],
  ['burn bridges', 'to destroy relationships or opportunities in a way that cannot be undone', 3],
  ['cut to the chase', 'to get to the point without wasting time', 3],
  ['draw a blank', 'to be unable to remember or think of anything', 3],
  ['face the music', 'to accept the unpleasant consequences of one’s actions', 3],
  ['get a taste of your own medicine', 'to be treated the way you have treated others, especially badly', 3],
  ['hit the sack', 'to go to bed', 3],
  ['in the heat of the moment', 'acting on impulse due to strong emotion, without thinking clearly', 3],
  ['keep something at bay', 'to prevent something from approaching or having an effect', 3],
];

const sat = [
  ['ubiquitous', 'present, appearing, or found everywhere'],
  ['ephemeral', 'lasting for a very short time'],
  ['pragmatic', 'dealing with things sensibly and realistically'],
  ['ambiguous', 'open to more than one interpretation; not clear'],
  ['meticulous', 'showing great attention to detail; very careful and precise'],
  ['candid', 'truthful and straightforward; frank'],
  ['resilient', 'able to withstand or recover quickly from difficult conditions'],
  ['arbitrary', 'based on random choice rather than reason or a system'],
  ['tenuous', 'very weak or slight'],
  ['austere', 'severe or strict in manner or appearance; without comforts or luxuries'],
  ['cogent', 'clear, logical, and convincing'],
  ['pervasive', 'spreading widely throughout an area or group of people'],
  ['superfluous', 'unnecessary, especially through being more than enough'],
  ['vindicate', 'to clear someone of blame or suspicion; to prove someone right'],
  ['zealous', 'having great energy or enthusiasm in pursuit of a cause'],
  ['benevolent', 'well meaning and kindly'],
  ['capricious', 'given to sudden and unaccountable changes of mood or behavior'],
  ['diligent', 'having or showing care and conscientiousness in one’s work or duties'],
  ['eloquent', 'fluent or persuasive in speaking or writing'],
  ['frugal', 'sparing or economical with money or food'],
  ['ostensible', 'appearing or claiming to be true, but not necessarily so', 3],
  ['perfunctory', 'carried out with minimum effort or reflection, done merely as a routine duty', 3],
  ['obsequious', 'obedient or attentive to an excessive or servile degree', 3],
  ['recalcitrant', 'having an obstinately uncooperative attitude toward authority or discipline', 3],
  ['sycophant', 'a person who acts obsequiously toward someone important in order to gain advantage', 3],
  ['esoteric', 'intended for or understood by only a small number of people with specialized knowledge', 3],
  ['mendacious', 'not telling the truth; lying', 3],
  ['garrulous', 'excessively talkative, especially on trivial matters', 3],
  ['taciturn', 'reserved or uncommunicative in speech; saying little', 3],
  ['vitriolic', 'filled with bitter criticism or malice', 3],
  ['quixotic', 'exceedingly idealistic; unrealistic and impractical', 3],
  ['hegemony', 'leadership or dominance, especially by one group or country over others', 3],
  ['sanguine', 'optimistic or positive, especially in a difficult situation', 3],
  ['pernicious', 'having a harmful effect, especially in a gradual or subtle way', 3],
  ['laconic', 'using very few words; concise to the point of seeming terse', 3],
  ['perspicacious', 'having keen insight and good judgment; mentally sharp', 5],
  ['obfuscate', 'to deliberately make something unclear or hard to understand', 5],
  ['surreptitious', 'done in a secretive or stealthy way to avoid being noticed', 5],
  ['vicissitude', 'a sudden or unexpected change in circumstances, often unpleasant', 5],
  ['assiduous', 'showing great care, attention, and diligence in one’s work', 5],
  ['pusillanimous', 'showing a lack of courage; cowardly', 5],
  ['magnanimous', 'generous or forgiving, especially toward a rival or lesser person', 5],
  ['nefarious', 'wicked or criminal in a way that is extremely evil', 5],
  ['cacophony', 'a harsh, jarring mixture of discordant sounds', 5],
  ['dichotomy', 'a division or contrast between two things that are opposed or entirely different', 5],
  ['verisimilitude', 'the appearance of being true or real', 5],
  ['obstreperous', 'noisy and difficult to control; stubbornly defiant', 5],
  ['loquacious', 'tending to talk a great deal; very talkative', 5],
  ['mellifluous', 'a sound that is sweet and smooth, pleasing to hear', 5],
  ['trenchant', 'vigorous or incisive in expression or thought; sharply perceptive', 5],
  ['inexorable', 'impossible to stop or prevent; relentless', 5],
  ['peripatetic', 'traveling from place to place, especially working or based in various locations', 5],
  ['abstruse', 'difficult to understand; obscure', 5],
  ['sagacious', 'having or showing keen mental discernment and good judgment', 5],
  ['parsimonious', 'unwilling to spend money or use resources; extremely frugal', 5],
];

const phrases = [
  ['give someone the benefit of the doubt', 'to trust what someone says without proof, assuming they are telling the truth'],
  ['call it a day', 'to stop doing something for the rest of the day'],
  ['make ends meet', 'to have just enough money to cover basic expenses'],
  ['on the fence', 'undecided about something'],
  ['piece of cake', 'something very easy to do'],
  ['sit tight', 'to wait patiently and not take action for the moment'],
  ['throw in the towel', 'to give up on something'],
  ['touch base', 'to briefly make or renew contact with someone'],
  ['wing it', 'to do something without preparation, improvising as you go'],
  ['get the hang of it', 'to learn how to do something properly'],
  ['step up to the plate', 'to take responsibility and meet a challenge'],
  ['keep an eye on', 'to watch or monitor closely'],
  ['put it off', 'to postpone or delay something'],
  ['run out of time', 'to have no time left to finish something'],
  ['take it easy', 'to relax; to not work too hard'],
  ['in a nutshell', 'in summary; briefly stated'],
  ['come rain or shine', 'regardless of the circumstances; no matter what'],
  ['read between the lines', 'to understand the hidden meaning of something'],
  ['get cold feet', 'to become nervous or hesitant about doing something, especially right before it happens'],
  ['on top of things', 'well organized and in control of a situation'],
  ['against the clock', 'working with very little time remaining', 3],
  ['at the drop of a hat', 'immediately, without hesitation', 3],
  ['bite off more than you can chew', 'to take on more responsibility than you can handle', 3],
  ['cross that bridge when you come to it', 'to deal with a problem only when it actually happens', 3],
  ['go back on your word', 'to fail to keep a promise', 3],
  ['hold your horses', 'to wait and be patient', 3],
  ['let bygones be bygones', 'to forgive and forget past disagreements', 3],
  ['raise the bar', 'to set a higher standard for something', 3],
  ['see eye to eye', 'to agree with someone or share the same opinion', 3],
  ['take the plunge', 'to commit to a risky or difficult decision after hesitating', 3],
];

// Domain terminology/concepts for the tech and politics stories the app is
// grounded in — distinct from general idioms/SAT words/phrases so an article
// can be guaranteed to teach at least one term relevant to its actual topic.
const techTerms = [
  ['algorithm', 'a step-by-step set of instructions a computer follows to solve a problem or complete a task'],
  ['artificial intelligence', 'computer systems designed to perform tasks that normally require human intelligence, like understanding language or recognizing images'],
  ['cybersecurity', 'the practice of protecting computer systems and data from theft, damage, or unauthorized access'],
  ['encryption', 'the process of converting information into a code to prevent unauthorized people from reading it'],
  ['open-source', 'describes software whose original code is made freely available and may be redistributed and modified by anyone'],
  ['bandwidth', 'the amount of data that can be transmitted over a network connection in a given amount of time'],
  ['cloud computing', 'storing and accessing data and programs over the internet instead of on a local computer’s hard drive'],
  ['data breach', 'an incident where confidential or protected information is accessed or exposed without authorization'],
  ['machine learning', 'a type of artificial intelligence in which computers improve at a task by learning from data, rather than being explicitly programmed'],
  ['venture capital', 'money invested in early-stage companies that have high growth potential but also carry high risk'],
  ['startup', 'a newly established company, typically small and often built around a new idea or technology'],
  ['monopoly', 'a situation where a single company controls all or nearly all of a market, with little competition'],
  ['regulation', 'a rule or set of rules made by a government or authority to control how something is done'],
  ['antitrust', 'laws designed to prevent companies from unfairly limiting competition or forming monopolies'],
  ['privacy policy', 'a document explaining how a company collects, uses, and protects a user’s personal information'],
  ['biometric', 'relating to the measurement of unique physical features, like fingerprints or facial patterns, often used for identification'],
  ['autonomous', 'able to operate or make decisions independently, without direct human control, as in an "autonomous vehicle"'],
  ['disruptive innovation', 'a new product or technology that significantly changes how an industry works, often replacing older methods'],
];

const politicsTerms = [
  ['bipartisan', 'supported by or involving members of two major political parties'],
  ['legislation', 'laws that have been proposed or enacted by a governing body'],
  ['filibuster', 'a tactic used to delay or block a vote in a legislature, often by speaking for an extended period'],
  ['veto', 'the power of an official, such as a president, to reject a decision or piece of legislation'],
  ['constituency', 'a group of voters in a specific area represented by an elected official'],
  ['coalition', 'an alliance of political parties or groups working together, often to form a government or pass legislation'],
  ['sanctions', 'penalties, often economic, imposed by one country or group of countries on another to influence its behavior'],
  ['diplomacy', 'the practice of managing relationships and negotiations between countries'],
  ['referendum', 'a direct vote by citizens on a specific political question or proposed law'],
  ['incumbent', 'a person who currently holds a political office, especially when running for reelection'],
  ['lobbying', 'the act of trying to influence lawmakers’ decisions, often on behalf of a specific group or industry'],
  ['amendment', 'a formal change or addition made to a law, constitution, or other document'],
  ['sovereignty', 'the authority of a country to govern itself without outside interference'],
  ['austerity', 'government policies aimed at reducing spending and debt, often through cuts to public services'],
  ['gerrymandering', 'redrawing electoral district boundaries to unfairly favor one political party'],
  ['impeachment', 'a formal process to charge a public official with wrongdoing, potentially leading to removal from office'],
  ['summit', 'a formal meeting between heads of government or other high-level officials to discuss important issues'],
  ['geopolitics', 'the study of how geography, politics, and international relations influence each other'],
];

const cultureTerms = [
  ['blockbuster', 'a movie, book, or show that is extremely successful and popular with a wide audience'],
  ['critically acclaimed', 'praised by professional reviewers as being of very high quality'],
  ['box office', 'the total amount of money a film earns from ticket sales, or the place tickets are sold'],
  ['adaptation', 'a film, show, or play based on a book or other existing work'],
  ['ensemble cast', 'a group of actors who share roughly equal importance in a production, rather than one lead star'],
  ['streaming platform', 'an online service that delivers movies, shows, or music directly to viewers over the internet'],
  ['memoir', 'a book in which someone writes about their own life and experiences'],
  ['satire', 'the use of humor, irony, or exaggeration to criticize people, institutions, or ideas'],
  ['plot twist', 'an unexpected turn or surprising development in a story'],
  ['nostalgia', 'a sentimental longing for the past, often for a particular period or experience'],
  ['pop culture', 'ideas, images, and activities that reflect the common tastes of the general public at a given time'],
  ['iconic', 'widely recognized and admired as representing a particular idea, time, or style'],
  ['genre', 'a category of art, music, or literature defined by a particular style, form, or subject matter'],
  ['choreography', 'the sequence of steps and movements planned for a dance or performance'],
  ['retrospective', 'an exhibition or review that looks back over an artist’s or performer’s body of work'],
  ['collaboration', 'the act of working together with someone else to create or produce something'],
  ['viral', 'spreading very quickly and widely among people, especially online'],
  ['cultural phenomenon', 'something, such as a trend or work of art, that has a widespread and notable impact on society'],
];

function build(list, category) {
  return list.map(([term, definition, difficulty], i) => ({
    id: `${category}-${i + 1}`,
    term,
    category,
    definition,
    difficulty: difficulty ?? (i % 3) + 1,
  }));
}

function buildConcepts(list, topic) {
  return list.map(([term, definition], i) => ({
    id: `concept-${topic}-${i + 1}`,
    term,
    category: 'concept',
    topic,
    definition,
    difficulty: (i % 3) + 1,
  }));
}

export const VOCAB_BANK = [
  ...build(idioms, 'idiom'),
  ...build(sat, 'sat'),
  ...build(phrases, 'phrase'),
  ...buildConcepts(techTerms, 'technology'),
  ...buildConcepts(politicsTerms, 'politics'),
  ...buildConcepts(cultureTerms, 'culture'),
];

export function wordById(id) {
  return VOCAB_BANK.find((w) => w.id === id);
}
